version: "2.1"
services:
  mongo:
    image: mongo:3.2.4
    container_name: mongo-container
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
    - 27777:27777
    command: --smallfiles
    
  mongo-init:
    build: ./mongo-init
    links:
      - mongo
      
  mongo-client:
    image: mongoclient/mongoclient
    ports:
    - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27777
    links:
      - mongo

    
    

